// <auto-generated />
using LincleLINK.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LincleLINK.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LincleLinkDbContext))]
    partial class LincleLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LincleLINK.Core.Infrastructure.Persistence.InstanceDirectoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceName");

                    b.ToTable("InstanceDirectories", (string)null);
                });

            modelBuilder.Entity("LincleLINK.Core.Infrastructure.Persistence.InstanceEntity", b =>
                {
                    b.Property<string>("InstanceName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomLogoSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotalFileSizeString")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceName");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.ToTable("Instances", (string)null);
                });

            modelBuilder.Entity("LincleLINK.Core.Infrastructure.Persistence.InstanceFileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceName");

                    b.ToTable("InstanceFiles", (string)null);
                });

            modelBuilder.Entity("LincleLINK.Core.Infrastructure.Persistence.InstanceDirectoryEntity", b =>
                {
                    b.HasOne("LincleLINK.Core.Infrastructure.Persistence.InstanceEntity", null)
                        .WithMany("Directories")
                        .HasForeignKey("InstanceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LincleLINK.Core.Infrastructure.Persistence.InstanceFileEntity", b =>
                {
                    b.HasOne("LincleLINK.Core.Infrastructure.Persistence.InstanceEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("InstanceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LincleLINK.Core.Infrastructure.Persistence.InstanceEntity", b =>
                {
                    b.Navigation("Directories");

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
